# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.2"

[[constraint]]
  name = "github.com/gocolly/colly"
  version = "1.2.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "GamePriceApi"
[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.2.1"
